### Create User

POST http://localhost:3000/tasks
Content-Type: application/json

{
  "nome": "segunda tarefa",
  "data_de_execucao": "2022-06-22",
  "situacao": "pendente",
  "prioridade": "baixa",
  "data_de_conclusao": "2022-06-30"
}

### FindAll

GET http://localhost:3000/tasks

### FindOne

GET http://localhost:3000/tasks/62b375a825762051d7758ca6

### Update

PATCH http://localhost:3000/tasks/62b375a825762051d7758ca6
Content-Type: application/json

{
  "situacao": "finalizado",
  "prioridade": "media"
}

### Delete

DELETE http://localhost:3000/tasks/62b373af1c21666ebb1a57c9
